import { MovieWithMedia } from '../../src/modules/catalog/domain/repositories/movie.repository.interface';
import { TrendingShowItem } from '../../src/modules/catalog/domain/repositories/show.repository.interface';
import { MediaType } from '../../src/common/enums/media-type.enum';

export const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);

export const moviesFixture: MovieWithMedia[] = [
  {
    id: 'mid-1',
    mediaItemId: 'mid-1',
    tmdbId: 1,
    title: 'Movie One',
    slug: 'movie-one',
    overview: null,
    ingestionStatus: 'ready' as any,
    poster: null,
    backdrop: null,
    popularity: 100,
    releaseDate: new Date('2024-01-01'),
    videos: null,
    stats: {
      ratingoScore: 80,
      qualityScore: 0.7,
      popularityScore: 0.9,
      liveWatchers: null,
      totalWatchers: null,
    },
    externalRatings: {
      tmdb: { rating: 7, voteCount: 100 },
      imdb: null,
      trakt: { rating: 8, voteCount: 80 },
      metacritic: null,
      rottenTomatoes: null,
    },
    theatricalReleaseDate: daysAgo(3),
    digitalReleaseDate: daysAgo(5),
    runtime: null,
    genres: [{ id: 'g-action', name: 'Action', slug: 'action' }] as any,
  },
  {
    id: 'mid-2',
    mediaItemId: 'mid-2',
    tmdbId: 2,
    title: 'Movie Two',
    slug: 'movie-two',
    overview: null,
    ingestionStatus: 'ready' as any,
    poster: null,
    backdrop: null,
    popularity: 80,
    releaseDate: new Date('2023-06-01'),
    videos: null,
    stats: {
      ratingoScore: 60,
      qualityScore: 0.5,
      popularityScore: 0.6,
      liveWatchers: null,
      totalWatchers: null,
    },
    externalRatings: {
      tmdb: { rating: 6.5, voteCount: 50 },
      imdb: null,
      trakt: { rating: 7, voteCount: 40 },
      metacritic: null,
      rottenTomatoes: null,
    },
    theatricalReleaseDate: daysAgo(0),
    digitalReleaseDate: null,
    runtime: null,
    genres: [{ id: 'g-drama', name: 'Drama', slug: 'drama' }] as any,
  },
  {
    id: 'mid-3',
    mediaItemId: 'mid-3',
    tmdbId: 3,
    title: 'Movie Three',
    slug: 'movie-three',
    overview: null,
    ingestionStatus: 'ready' as any,
    poster: null,
    backdrop: null,
    popularity: 60,
    releaseDate: new Date('2022-01-01'),
    videos: null,
    stats: {
      ratingoScore: 50,
      qualityScore: 0.9,
      popularityScore: 0.4,
      liveWatchers: null,
      totalWatchers: null,
    },
    externalRatings: {
      tmdb: { rating: 9.1, voteCount: 1000 },
      imdb: null,
      trakt: { rating: 9, voteCount: 900 },
      metacritic: null,
      rottenTomatoes: null,
    },
    theatricalReleaseDate: daysAgo(10),
    digitalReleaseDate: null,
    runtime: null,
    genres: [
      { id: 'g-action', name: 'Action', slug: 'action' },
      { id: 'g-thriller', name: 'Thriller', slug: 'thriller' },
    ] as any,
  },
  {
    id: 'mid-4',
    mediaItemId: 'mid-4',
    tmdbId: 4,
    title: 'Movie Four',
    slug: 'movie-four',
    overview: null,
    ingestionStatus: 'ready' as any,
    poster: null,
    backdrop: null,
    popularity: 40,
    releaseDate: new Date('2019-01-01'),
    videos: null,
    stats: {
      ratingoScore: 40,
      qualityScore: 0.2,
      popularityScore: 0.2,
      liveWatchers: null,
      totalWatchers: null,
    },
    externalRatings: {
      tmdb: { rating: 4.1, voteCount: 5 },
      imdb: null,
      trakt: { rating: 4, voteCount: 4 },
      metacritic: null,
      rottenTomatoes: null,
    },
    theatricalReleaseDate: null,
    digitalReleaseDate: daysAgo(0),
    runtime: null,
    genres: [{ id: 'g-comedy', name: 'Comedy', slug: 'comedy' }] as any,
  },
];

// use any to allow extra fields (genres/popularity) for filtering/sorting fixtures
export const showsFixture: any[] = [
  {
    id: 'sid-1',
    mediaItemId: 'sid-1',
    type: MediaType.SHOW,
    slug: 'show-one',
    title: 'Show One',
    originalTitle: null,
    overview: null,
    ingestionStatus: 'ready' as any,
    primaryTrailerKey: null,
    poster: null,
    backdrop: null,
    releaseDate: new Date('2024-03-01'),
    isNew: true,
    isClassic: false,
    status: 'Returning Series',
    totalSeasons: 3,
    lastAirDate: daysAgo(5),
    nextAirDate: null,
    stats: {
      ratingoScore: 75,
      qualityScore: 0.6,
      popularityScore: 0.8,
      liveWatchers: null,
      totalWatchers: null,
    } as any,
    externalRatings: {
      tmdb: { rating: 8.5, voteCount: 1500 },
      imdb: { rating: 8.2, voteCount: 2000 },
      trakt: { rating: 8.0, voteCount: 1200 },
      metacritic: null,
      rottenTomatoes: null,
    } as any,
    showProgress: {
      lastAirDate: daysAgo(5),
      nextAirDate: null,
      season: 3,
      episode: 1,
      label: 'S3E1',
    },
    genres: [{ id: 'g-drama', name: 'Drama', slug: 'drama' }] as any,
    popularity: 90,
  },
  {
    id: 'sid-2',
    mediaItemId: 'sid-2',
    type: MediaType.SHOW,
    slug: 'show-two',
    title: 'Show Two',
    originalTitle: null,
    overview: null,
    ingestionStatus: 'ready' as any,
    primaryTrailerKey: null,
    poster: null,
    backdrop: null,
    releaseDate: new Date('2022-02-01'),
    isNew: false,
    isClassic: false,
    status: 'Canceled',
    totalSeasons: 2,
    lastAirDate: new Date('2023-01-01'),
    nextAirDate: null,
    stats: {
      ratingoScore: 55,
      qualityScore: 0.4,
      popularityScore: 0.3,
      liveWatchers: null,
      totalWatchers: null,
    } as any,
    externalRatings: {
      tmdb: { rating: 6, voteCount: 100 },
      imdb: { rating: 5.8, voteCount: 250 },
      trakt: { rating: 6.2, voteCount: 80 },
      metacritic: null,
      rottenTomatoes: null,
    } as any,
    showProgress: {
      lastAirDate: new Date('2023-01-01'),
      nextAirDate: null,
      season: 2,
      episode: 10,
      label: 'S2E10',
    },
    genres: [{ id: 'g-action', name: 'Action', slug: 'action' }] as any,
    popularity: 20,
  },
];
