/**
 * Standardized error codes for the API.
 * Used in error responses for client-side handling.
 */
export enum ErrorCode {
  // Validation errors (400)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',

  // Not found errors (404)
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  STATS_NOT_FOUND = 'STATS_NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REPLY_NOT_FOUND = 'REPLY_NOT_FOUND',

  // Conflict errors (409)
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REPORT_ALREADY_EXISTS = 'REPORT_ALREADY_EXISTS',
  REPORT_ALREADY_RESOLVED = 'REPORT_ALREADY_RESOLVED',

  // Business rule violations (400)
  REPLY_MAX_DEPTH_EXCEEDED = 'REPLY_MAX_DEPTH_EXCEEDED',

  // Rate limiting (429)
  RATE_LIMITED = 'RATE_LIMITED',

  // External API errors (502/503)
  TMDB_API_ERROR = 'TMDB_API_ERROR',
  TRAKT_API_ERROR = 'TRAKT_API_ERROR',
  OMDB_API_ERROR = 'OMDB_API_ERROR',
  TVMAZE_API_ERROR = 'TVMAZE_API_ERROR',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Database errors (500)
  DATABASE_ERROR = 'DATABASE_ERROR',

  // Feature disabled (422)
  FEATURE_DISABLED = 'FEATURE_DISABLED',

  // Generic errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
}
