import type { FxRarity } from '../../types';

export type RarityVisualProfile = {
  ribbon: number;
  overlayTint: number;
  medalFill: number;
  medalStroke: number;
  sparkPrimary: number;
  sparkSecondary: number;
  debrisColor: number;
  smokeColor: number;
  titleColor: number;
  labelColor: number;
  durationMs: number;
  flashAlpha: number;
  vignette: number;
  sparkCount: number;
  debrisCount: number;
  smokeCount: number;
  settleScale: number;
  entryOffsetY: number;
  shakePx: number;
  cameraPunch: number;
  shockwave: boolean;
  doubleBurst: boolean;
  glitchGain: number;
};

export const RARITY_VISUAL: Record<FxRarity, RarityVisualProfile> = {
  common: {
    ribbon: 0x353b45,
    overlayTint: 0x404a58,
    medalFill: 0x737a86,
    medalStroke: 0xc7d0de,
    sparkPrimary: 0xd8e0ea,
    sparkSecondary: 0xa7b1be,
    debrisColor: 0x4d5968,
    smokeColor: 0x657386,
    titleColor: 0xe3e9f2,
    labelColor: 0xc1cbd9,
    durationMs: 880,
    flashAlpha: 0.06,
    vignette: 0.14,
    sparkCount: 10,
    debrisCount: 2,
    smokeCount: 6,
    settleScale: 1.03,
    entryOffsetY: 18,
    shakePx: 0,
    cameraPunch: 0,
    shockwave: false,
    doubleBurst: false,
    glitchGain: 1,
  },
  rare: {
    ribbon: 0x1f4f8a,
    overlayTint: 0x2268b8,
    medalFill: 0x4f79b2,
    medalStroke: 0xbfdcff,
    sparkPrimary: 0x93d0ff,
    sparkSecondary: 0x4aa9ff,
    debrisColor: 0x355c90,
    smokeColor: 0x446a9d,
    titleColor: 0xe3f2ff,
    labelColor: 0xbfdcff,
    durationMs: 1060,
    flashAlpha: 0.16,
    vignette: 0.24,
    sparkCount: 18,
    debrisCount: 8,
    smokeCount: 10,
    settleScale: 1.08,
    entryOffsetY: 26,
    shakePx: 0.55,
    cameraPunch: 0.95,
    shockwave: false,
    doubleBurst: false,
    glitchGain: 1,
  },
  epic: {
    ribbon: 0x4a2b70,
    overlayTint: 0x6c3eb0,
    medalFill: 0x7d57b7,
    medalStroke: 0xe0c5ff,
    sparkPrimary: 0xd6a8ff,
    sparkSecondary: 0xa86fff,
    debrisColor: 0x553985,
    smokeColor: 0x6a4d99,
    titleColor: 0xf1e1ff,
    labelColor: 0xd8c0f4,
    durationMs: 1320,
    flashAlpha: 0.22,
    vignette: 0.3,
    sparkCount: 30,
    debrisCount: 16,
    smokeCount: 16,
    settleScale: 1.11,
    entryOffsetY: 34,
    shakePx: 1.1,
    cameraPunch: 1.8,
    shockwave: true,
    doubleBurst: false,
    glitchGain: 1,
  },
  legendary: {
    ribbon: 0x6b3a18,
    overlayTint: 0x9a531f,
    medalFill: 0xd1883a,
    medalStroke: 0xffe2ae,
    sparkPrimary: 0xffd48b,
    sparkSecondary: 0xffa23d,
    debrisColor: 0x8f5525,
    smokeColor: 0x9d6a3c,
    titleColor: 0xffefc7,
    labelColor: 0xf2cf94,
    durationMs: 1580,
    flashAlpha: 0.28,
    vignette: 0.42,
    sparkCount: 44,
    debrisCount: 28,
    smokeCount: 26,
    settleScale: 1.18,
    entryOffsetY: 56,
    shakePx: 2.6,
    cameraPunch: 4.6,
    shockwave: true,
    doubleBurst: true,
    glitchGain: 1,
  },
};
