#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx turbo run lint --filter=api && \
npm --prefix apps/api run typecheck && \
npx turbo run build --filter=api && \
npx turbo run test --filter=api -- --runInBand && \
npx turbo run test --filter=web-client
